version: 0.0
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/html/  # Nginx's default static content directory
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root
